Fix indentation

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -35,51 +35,51 @@ script:
 # Deploy images to dockerhub
 after_success:
 - | # Check if it is not PULL REQUEST
-  if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then
-      # Generate tags for images
-      IMG_TAG_SUFFIX=""; 
-      IMG_TAGL_SUFFIX="";
+    if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then
+        # Generate tags for images
+        IMG_TAG_SUFFIX=""; 
+        IMG_TAGL_SUFFIX="";
 
-      if [[ $USE_IMG_VER == "true" ]] && [[ $IMG_VERSION != "" ]]; then
-          if [[ $IMG_BRANCH != "master" ]]; then
-              IMG_TAG_SEP="-";
-          fi
-          IMG_TAG_SUFFIX="${IMG_TAG_SEP}${IMG_VERSION}";
-          IMG_TAGL_SUFFIX="${IMG_TAG_SEP}latest";
-      fi
-      if [[ $IMG_BRANCH != "master" ]]; then
-          IMG_TAG="${IMG_BRANCH}${IMG_TAG_SUFFIX}";
-          IMG_TAGL="${IMG_BRANCH}${IMG_TAGL_SUFFIX}";
-      else
-          IMG_TAG="${IMG_TAG_SUFFIX}";
-          IMG_TAGL="latest";
-      fi
+        if [[ $USE_IMG_VER == "true" ]] && [[ $IMG_VERSION != "" ]]; then
+            if [[ $IMG_BRANCH != "master" ]]; then
+                IMG_TAG_SEP="-";
+            fi
+            IMG_TAG_SUFFIX="${IMG_TAG_SEP}${IMG_VERSION}";
+            IMG_TAGL_SUFFIX="${IMG_TAG_SEP}latest";
+        fi
+        if [[ $IMG_BRANCH != "master" ]]; then
+            IMG_TAG="${IMG_BRANCH}${IMG_TAG_SUFFIX}";
+            IMG_TAGL="${IMG_BRANCH}${IMG_TAGL_SUFFIX}";
+        else
+            IMG_TAG="${IMG_TAG_SUFFIX}";
+            IMG_TAGL="latest";
+        fi
 
-      # Don't use same tag twice (case when no version)
-      if [[ $IMG_TAG == $IMG_TAGL ]]; then 
-          IMG_TAG="";
-      fi
+        # Don't use same tag twice (case when no version)
+        if [[ $IMG_TAG == $IMG_TAGL ]]; then 
+            IMG_TAG="";
+        fi
 
-      # Authenticate with docker
-      if [[ $DOCKER_USERNAME != "" ]] && [[ $DOCKER_PASSWORD != "" ]]; then
-          echo "$DOCKER_PASSWORD" | ${SUDO_CMD} docker login -u "$DOCKER_USERNAME" --password-stdin;
+        # Authenticate with docker          
+        if [[ $DOCKER_USERNAME != "" ]] && [[ $DOCKER_PASSWORD != "" ]]; then
+            echo "$DOCKER_PASSWORD" | ${SUDO_CMD} docker login -u "$DOCKER_USERNAME" --password-stdin;
 
-          if [ $? -ne 0 ]; then
-              echo 'Failed to login into dockerhub';
-              exit 0;
-          fi
-          # Push images
-          if [[ $IMG_TAG != "" ]]; then
-              ${SUDO_CMD} docker tag ${IMG_NAME} ${IMG_NAME}:${IMG_TAG};
-              ${SUDO_CMD} docker push ${IMG_NAME}:${IMG_TAG};
-          fi
-          if [[ $IMG_TAGL != "" ]]; then
-              ${SUDO_CMD} docker tag ${IMG_NAME} ${IMG_NAME}:${IMG_TAGL};
-              ${SUDO_CMD} docker push ${IMG_NAME}:${IMG_TAGL};
-          fi
-          echo 'Pushed to dockerhub';
-      else
-          echo 'No credentials to login in dockerhub';
-      fi
-  fi
+            if [ $? -ne 0 ]; then
+                echo 'Failed to login into dockerhub';
+                exit 0;
+            fi
+            # Push images
+            if [[ $IMG_TAG != "" ]]; then
+                ${SUDO_CMD} docker tag ${IMG_NAME} ${IMG_NAME}:${IMG_TAG};
+                ${SUDO_CMD} docker push ${IMG_NAME}:${IMG_TAG};
+            fi
+            if [[ $IMG_TAGL != "" ]]; then
+                ${SUDO_CMD} docker tag ${IMG_NAME} ${IMG_NAME}:${IMG_TAGL};
+                ${SUDO_CMD} docker push ${IMG_NAME}:${IMG_TAGL};
+            fi
+            echo 'Pushed to dockerhub';
+        else
+            echo 'No credentials to login in dockerhub';
+        fi
+    fi
 
